# Generated by Django 4.1.5 on 2023-03-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('originator', models.CharField(max_length=100)),
                ('date_of_rec', models.DateField()),
                ('time_of_rec', models.TimeField()),
                ('datetime_of_action', models.DateTimeField(auto_now_add=True)),
                ('action_taken_by', models.CharField(max_length=10)),
                ('receiver_receiving_time', models.TimeField(blank=True, null=True)),
                ('group', models.IntegerField()),
                ('security_grade', models.CharField(max_length=50)),
                ('dispatched', models.BooleanField(default=False)),
                ('received_by', models.ManyToManyField(blank=True, related_name='receivedd', to='unit.acknowledgement', verbose_name='User who received')),
                ('receiver_unit', models.ManyToManyField(related_name='receiverss', to=settings.AUTH_USER_MODEL, verbose_name='receiver_unit')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senderrr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
